version: '3'

services:
  web: 
    build: .
    expose:
      - 3000

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    ports:
      - 1337:80
    depends_on:
      - web
    